### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ampuscas**
supersedes #184

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by ampuscas** [comment]
@jmMeessen could you please approve this PR?
I have created this PR that supersedes #184 for merging master, fixing the conflicts and updating dependencies as the build was failing due to Maven enforcer rule

**Comment by basil** [comment]
Suggest closing in favor of #200.

**Comment by basil** [comment]
I do not think this PR should be merged now that PR #200 has been merged. The only change that remains in this PR after #200 is the bump of the Jenkins baseline to 2.332.x. While that is not necessarily a bad thing, I can't think of a reason why it is needed at the present time, and it effectively locks out users of older lines (including `jenkinsci/bom`) from receiving updates. If testing against recent cores is needed and what we already do in `jenkinsci/bom` is not sufficient, an additional branch could be added to this repository's `Jenkinsfile`.

**Comment by ampuscas** [comment]
@jmMeessen @basil thank you, I am closing this PR as the PR #200 solves the problems I was addressing with this PR

**Pull request closed without merging**
