### PR TITLE
[JENKINS-27152] Use a standardized directory for managed files

### PR DESCRIPTION
**Pull request by jglick**
Matches jenkinsci/docker-workflow-plugin#33.

@reviewbybees

### CODE REVIEW

**Comment by ndeloof** [comment]
:bee:

**Comment by jglick** [comment]
The test failure seems random.

**Comment by jglick** [comment]
Indeed the test passes for me locally. I think I recall seeing a local failure once. No obvious relationship to the changes in this PR.

**Comment by cyrille-leclerc** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Comment by cyrille-leclerc** [comment]
Successfully tested on Jenkins ver. 1.642.2.1


```groovy
#!groovy
docker.image('cloudbees/java-build-tools:0.0.6').inside {

    wrap([$class: 'ConfigFileBuildWrapper', managedFiles: [[fileId: 'git-config-file', variable: 'GIT_CONFIG']]]) {
        sh "env"
        sh "ls -al /tmp"
        sh 'cat $GIT_CONFIG'
        sh "cat \$GIT_CONFIG" 
    }
}
```

```
Console Output

Started by user admin
[Pipeline] Allocate node : Start
Running on jenkins-agent.beesshop.org in /home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider
[Pipeline] node {
[Pipeline] sh
[test-config-file-provider] Running shell script
+ docker inspect -f . cloudbees/java-build-tools:0.0.6
.
[Pipeline] Run build steps inside a Docker container : Start
$ docker run -t -d -u 1000:1000 -w /home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider -v /home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider:/home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider:rw -v /home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider@tmp:/home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider@tmp:rw -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** cloudbees/java-build-tools:0.0.6 cat
[Pipeline] withDockerContainer {
[Pipeline] General Build Wrapper : Start
provisoning config files...
copy managed file [git-config-file] to file:/home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider@tmp/config6033766642048277871tmp
[Pipeline] wrap {
[Pipeline] sh
[test-config-file-provider] Running shell script
+ env
JENKINS_HOME=/var/lib/jenkins
HOSTNAME=0b282318cd2f
HUDSON_URL=http://jenkins-aws.beesshop.org/
HOME=/home/jenkins
BUILD_URL=http://jenkins-aws.beesshop.org/job/tests/job/test-config-file-provider/5/
JENKINS_SERVER_COOKIE=durable-c9184776e95e8b7450219cc8351237c0
MAVEN_HOME=/usr/share/maven
SCREEN_HEIGHT=1020
NODE_NAME=jenkins-agent.beesshop.org
EXECUTOR_NUMBER=0
TERM=xterm
BUILD_DISPLAY_NAME=#5
HUDSON_HOME=/var/lib/jenkins
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SCREEN_DEPTH=24
BUILD_ID=5
BUILD_TAG=jenkins-tests-test-config-file-provider-5
DISPLAY=:99.0
JENKINS_URL=http://jenkins-aws.beesshop.org/
JOB_URL=http://jenkins-aws.beesshop.org/job/tests/job/test-config-file-provider/
GIT_CONFIG=/home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider@tmp/config6033766642048277871tmp
BUILD_NUMBER=5
HUDSON_SERVER_COOKIE=50c56f61118cbbec
MAVEN_VERSION=3.3.9
CLASSPATH=
JOB_NAME=tests/test-config-file-provider
SCREEN_WIDTH=1360
PWD=/home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider
[Pipeline] sh
[test-config-file-provider] Running shell script
+ cat /home/ubuntu/jenkins-aws-home/workspace/tests/test-config-file-provider@tmp/config6033766642048277871tmp
[user]
	name = Cyrille Le Clerc
	email = cyrille@cyrilleleclerc.com[Pipeline] } //wrap
Deleting 1 temporary files
[Pipeline] General Build Wrapper : End
````

**Comment by jglick** [comment]
@imod did you get a chance to look at this?

**Comment by imod** [comment]
yep, this looks good from my side - just did not have the chance to merge it yet

**Pull request merged**
