### PR TITLE
[JENKINS-42262] Add API where extension point could implement own logic for the content

### PR DESCRIPTION
**Pull request by nfalco79**
Implementation where ManagedFile is elite to public API

### CODE REVIEW

**Comment by nfalco79** [comment]
I do like so much create a ManagedFile bean to be use in ManagedFileUtil because ManagedFile#variable field is not used. and API consumer has no idea on how to thread it.

**Comment by nfalco79** [comment]
Maybe we could create a basic java bean to be use in API and ManagedFile could extend it adding variable field and the descriptor annotated @Symbol 

Let me do a try this evening after work

**Comment by nfalco79** [comment]
Refactor completed, the ConfigFile is the java bean in the signature of ConfigFileManager (90% of ManagedFileUtil) that handle provision for a single ConfigFile.
ManagedFile extends ConfigFile plus "variable" field. Do not care about javadoc

**Comment by AnneTheAgile** [comment]
@nfalco79 , would this PR help me to be able to add the feature of editing a config file from various jobs? I am noodling how to solve some shared state that I wish to modify, eg increment for example. 
ty! AnneTheAgile

**Comment by nfalco79** [comment]
The PR enable this plugin to reproduce the same content of plugins that extend this one exposing an API that simply the provision of config file for extensions.

**Comment by nfalco79** [comment]
@imod any comment on this?

**Comment by imod** [comment]
@nfalco79 I'm very sorry I did not respond in time yet, but this really looks good. Please give me a few more days and I will take a closer look again.

**Comment by nfalco79** [comment]
In our server are installed (since a mounth) a customisation of this plugin built on this branch and the NodeJS plugin build on branch that use these new API.

We have a 6/7 Maven/Freetype jobs that use maven with the frontend-maven-plugin to build some WAB
These job are configured to use:
- settings.xml by the Maven Step to point our organisation artifactory
- toolchains.xml by config-file-provide step used during maven build (because of maven tycho).
- npm config file (extension) by config-file-provide step to change npm registry to point our organisation artifactory

All works great

**Comment by imod** [comment]
@nfalco79 this looks good, the only thing I was not yet able to fully check is the compatibility with the with the pipeline maven plugin (https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Maven+Plugin) I think it is OK, but I wanna check...

cc @cyrille-leclerc

**Comment by imod** [comment]
an other plugin which must be checked it the job DSL plugin - but as I'm not really familiar with it, its hard to say for me...  @daspilker

**Comment by nfalco79** [comment]
Follow the multibranch project we used to test pull request.
```
node('nodejs') {
	stage ('Checkout') {
		checkout scm
	}

	stage ('Build') {
		ansiColor('xterm') {
			configFileProvider([configFile(fileId: 'jdk.toolchains', replaceTokens: true, variable: 'TOOLCHAINS_XML'), configFile(fileId: 'artifactory.npm', variable: 'NPM_CONFIG_USERCONFIG')]) {
				withMaven( jdk: 'JDK 1.8', maven: 'Maven 3.3', mavenSettingsConfig: 'artifactory.prod' ) {
					def defaultMvnArgs = "--batch-mode -V -U"

					withSonarQubeEnv {
						def sonarProperties = "-Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_AUTH_TOKEN}"
						if ( !(env.BRANCH_NAME == 'master') ) {
							sonarProperties += "-Dsonar.analysis.mode=preview"
						}
						echo "PROPS = $sonarProperties"

						sh 'mvn ${defaultMvnArgs} clean install ${SONAR_MAVEN_GOAL} ${sonarProperties}'
					}
				}
			}
		}
	}
}
```

The only defect (not related to these changes) is that confguration files are not deleted on Jekins node. They are placed in myrepo_featureXYZ@tmp and never deleted.

**Comment by cyrille-leclerc** [comment]
@imod @nfalco79 I have added tons of integration tests in the pipeline-maven-plugin, please let may run those with this change.

**Comment by nfalco79** [comment]
So if I understand right, I don't have nothing to do?
Just wait some kind of approval of @daspilker and pipeline test from @cyrille-leclerc ?

**Comment by imod** [comment]
@daspilker does the DSL plugin include adequate tests to check if the config-file-provider plugin is working fine from a DSL point POV? If so, then I'll run the test the changes of this PR...

**Comment by daspilker** [comment]
@imod Job DSL has some tests for config-file-provider, but the test coverage is not great. As far as I see this PR does not change the API that Job DSL uses, so it should be no problem.

**Comment by imod** [comment]
@daspilker perfect, thanks!

@cyrille-leclerc did you have the chance to run the tests?

**Comment by cyrille-leclerc** [comment]
Works for me! Successfully tested with pipeline-maven-plugin 2.1.0.

**Comment by nfalco79** [comment]
Hi imod, any plan for a new release? So I can release nodejs based on the new APIs

**Comment by imod** [comment]
@nfalco79 yep, actually its planned for today

**Comment by imod** [comment]
@nfalco79 done...

**Pull request merged**
