### PR TITLE
Adjust credentials masking tests for base64 masking improvement

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Adjust credentials masking tests for base64 masking improvement

Credentials masking now includes masking of base64 credentials.  The tests were using a very short user name, "bot".  The base64 encoding of that short user name matches with other log content and causes the tests to fail.

Use a longer user name and a longer password in the test so that spurious matches are much less likely.

### Testing done

Confirmed the test fails when I run without b36d0a7623206ffaf2f7dd4d4850414d308cd014

`mvn clean -Dtest=MavenSettingsConfigTest verify`

Confirmed that tests pass when I include b36d0a7623206ffaf2f7dd4d4850414d308cd014

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by MarkEWaite** [comment]
More details are available in:

* https://github.com/jenkinsci/bom/issues/2513
* https://github.com/jenkinsci/bom/issues/2514

**Comment by jglick** [comment]
Sorry, accidentally clicked **Re-run**! FTR https://github.com/jenkinsci/config-file-provider-plugin/pull/296/checks?check_run_id=16858023665

```
java.io.IOException: Illegal base64 character 0x2a
	at java.base/java.util.Base64$DecInputStream.read(Base64.java:1160)
	at java.base/java.io.DataInputStream.read(DataInputStream.java:151)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at hudson.util.IOUtils.skip(IOUtils.java:90)
	at hudson.console.ConsoleNote.skip(ConsoleNote.java:311)
	at hudson.console.PlainTextConsoleOutputStream.eol(PlainTextConsoleOutputStream.java:67)
	at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:61)
	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:57)
	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:75)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:92)
	at org.kohsuke.stapler.framework.io.LargeText.writeLogTo(LargeText.java:233)
	at hudson.console.AnnotatedLargeText.writeLogTo(AnnotatedLargeText.java:164)
	at org.jvnet.hudson.test.JenkinsRule.getLog(JenkinsRule.java:1536)
	at org.jvnet.hudson.test.JenkinsRule.assertLogNotContains(JenkinsRule.java:1525)
	at org.jenkinsci.plugins.configfiles.maven.MavenSettingsConfigTest.freestyleWithCredentials(MavenSettingsConfigTest.java:157)
```

Regardless of whether the regression is caused by https://github.com/jenkinsci/credentials-binding-plugin/pull/269, I think the error is also fixed by https://github.com/jenkinsci/jenkins/pull/8378.

**Comment by MarkEWaite** [comment]
> Regardless of whether the regression is caused by [jenkinsci/credentials-binding-plugin#269](https://github.com/jenkinsci/credentials-binding-plugin/pull/269), I think the error is also fixed by [jenkinsci/jenkins#8378](https://github.com/jenkinsci/jenkins/pull/8378).

That explains why the failure is not visible in the weekly release line and is only visible in the LTS release line.  Thanks very much for pointing to that change.  I've confirmed that this pull request passes when built with:

  `mvn -Djenkins.version=2.420 -Dtest=MavenSettingsConfigTest verify`

It fails when built with:

  `mvn -Djenkins.version=2.419 -Dtest=MavenSettingsConfigTest verify`

Jenkins 2.420 is the first weekly release that includes the fix in  [jenkinsci/jenkins#8378](https://github.com/jenkinsci/jenkins/pull/8378).

I think that the next baseline Jenkins version for the config-file-provider plugin should be 2.387.3 so that it does not use too new a version.  If the next baseline Jenkins version for the config-file-provider plugin is anything less than Jenkins 2.420, then I think we will want some change to the config-file-provider tests so that they pass on the LTS baselines.  That change could be as simple as "skip the test if the Jenkins version is too old", but I think that we need the tests to pass.

Does that make sense to you @jglick or is there a better way to handle the failing config-file-provider tests when they run with the current credentials binding plugin in an older Jenkins release?

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/pull/8378 merely prevents a corrupted console note from breaking log streaming. Why the note became corrupted to begin with is another question; it sounds like https://github.com/jenkinsci/credentials-binding-plugin/pull/269 introduced a genuine regression to production code, by accidentally masking some snippet of serialized `ConsoleNote` that was unrelated to any secrets in scope. Perhaps the secret was very short and its Base64 form happens to appear in other unrelated contexts by coincidence, in which case there should be some minimum length requirement perhaps. Someone will need to debug the test to see exactly what is getting masked and why.

**Comment by Kevin-CB** [comment]
> Does that make sense to you @jglick or is there a better way to handle the failing config-file-provider tests when they run with the current credentials binding plugin in an older Jenkins release?

Using a longer secret for `bot` should fix this issue; something like `bot123` works fine for me.

**Comment by MarkEWaite** [comment]
I've modified the tests as suggested by @Kevin-CB and confirmed that it now passes with Jenkins 2.419.  Changes are in b36d0a7623206ffaf2f7dd4d4850414d308cd014

**Comment by MarkEWaite** [comment]
> > Does that make sense to you @jglick or is there a better way to handle the failing config-file-provider tests when they run with the current credentials binding plugin in an older Jenkins release?
> 
> Using a longer secret for `bot` should fix this issue; something like `bot123` works fine for me.

@Kevin-CB do you also want to consider the addition of a minimum length criteria to the base64 masking in the credentials binding plugin?  I think that the suggestion from @jglick may help avoid user complaints when they use a very short user name or a very short password.

**Comment by MarkEWaite** [comment]
@alecharp if you'd be willing to label this as `developer`, review it, and if approved, merge it, that will allow me to remove the plugin bill of materials workaround that I inserted in:

* https://github.com/jenkinsci/bom/pull/2514

**Review by alecharp — APPROVED** [review]

**Comment by alecharp** [comment]
Looks simple enough. Thank you @MarkEWaite.

**Comment by jglick** [comment]
> do you also want to consider the addition of a minimum length criteria to the base64 masking

This might be prudent, though you also have to ask why you are trying to mask such short secrets to begin with—clearly they would not be secure. For usernames, we guide users to disable username masking for newly created credentials, but continue to mask older credentials unless and until the user ops out.

The particular issue could I think also be addressed by disabling the Base64 masker on lines containing the magic header sequence for `ConsoleNote`, since we would never expect a user secret to occur (much less in Base64-encoded form) in a line that contains a note. That would prevent notes from becoming corrupted. You could still have spurious masking of short sequences in other parts of the log which would be annoying; of course this could also occur with the literal pattern factory, if you just happened to have a “password” like `123` that winds up occurring in all sorts of unrelated places.

**Comment by Kevin-CB** [comment]
I'm tracking this issue under [JENKINS-72035](https://issues.jenkins.io/browse/JENKINS-72035).

**Pull request merged**
