### PR TITLE
Add config file filtering: jenkins job env variables found in the con…

### PR DESCRIPTION
**Pull request by osthus-dm**
…fig files are replaced with their values. To avoid issues with Maven properties, use $VARIABLE, e.g. $WORKSPACE, inside the config files.

### CODE REVIEW

**Comment by imod** [comment]
@osthus-dm sorry for the late response...

I'm not quite sure what issue you try to solve here, can you explain a bit more?

**Comment by osthus-dm** [comment]
it is replacing placeholders in the config file with the env. values of the current execution environment during the copy process.

**Comment by imod** [comment]
I think it would be better to integrate the TokenMacro Plugin to do so: https://wiki.jenkins-ci.org/display/JENKINS/Token+Macro+Plugin

**Comment by osthus-dm** [comment]
ah, you suggest to use the token-replace mechanism offered by the TokenMacro plugin instead of the way I implemented it? I was not aware of the TokeMacro Plugin, but it indeed looks like it would be a perfect fit to use it in this case. 

So what are the next steps? Are you implementing this or should I (providing that I get time to do so) implement this and create a new pull request? I cannot estimate the effort for this, would have to read some docu first.

**Comment by imod** [comment]
yes, thats my suggestion...
you can easily adopt your PR, it should not be a big thing - just look some lines above your changes in the same file, the TokenMacro plugin is already used to replace tokens in the `targetLocation` https://github.com/OSTHUS/config-file-provider-plugin/blob/f0536a9ff503858cbd9fc5f89932865622c8cd35/src/main/java/org/jenkinsci/plugins/configfiles/buildwrapper/ManagedFileUtil.java#L93

**Comment by imod** [comment]
implemented with https://github.com/jenkinsci/config-file-provider-plugin/commit/881ef0509467487b22bcec8674bc56f49261d4bb - released with version 2.11

**Comment by osthus-dm** [comment]
nice, i'll give it a try

**Pull request closed without merging**
