### PR TITLE
Update `Jenkinsfile` and plugin parent POM

### PR DESCRIPTION
**Pull request by basil**
This is required for https://github.com/jenkinsci/stapler/pull/452 so that tests continue passing in this plugin and in BOM.

### CODE REVIEW

**Comment by basil** [comment]
Used my admin powers to replay the build with the `Jenkinsfile` changes here: https://ci.jenkins.io/job/Plugins/job/config-file-provider-plugin/job/PR-267/2/

**Comment by basil** [comment]
@jenkinsci/config-file-provider-plugin-developers Can this please be merged & released?

**Comment by alecharp** [comment]
I cannot do a release right now. I'll let @jmMeessen do one.

**Comment by basil** [comment]
BOM test suite is now broken due to a lack of release of this PR.

**Comment by jglick** [comment]
https://github.com/jenkinsci/config-file-provider-plugin/releases/tag/938.ve2b_8a_591c596

**Pull request merged**
